spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5332/book
    username: test
    password: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083